spring:
  application:
    name: aweather-mobile-web  
  main:
    allow-bean-definition-overriding: true

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000