spring:
  cloud:
    config:
      # 分布式配置中心服务的地址和端口号
      uri: http://localhost:8888
      # git仓库上对应上传的配置文件的名称
      name: user-application
      # 对应仓库分支
      label: master
      # 开发环境(开发,测试,生产)
#      profile: dev
